title: Bainian Liu's Personal Website
page-top-title: Bainian Liu
top-section-bg-text: Passion Fuels Tomorrow
home-subtitle: Bainian Liu&ensp;|&ensp;QianQ Sky
copyright-text: '&copy; Bainian Liu 2023-2025. All Rights Reserved.'
